version: '3.9'

services:
  postgresql_database:
    container_name: app-lite-test
    image: postgres:latest
    environment:
      - POSTGRES_USER=test-lite-u
      - POSTGRES_PASSWORD=test-lite-p
      - POSTGRES_DB=test-lite
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: